Configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,11 @@
 #!/usr/bin/env sh
 
+PKG_DEB_NAME="librdkafka-dev"
+PKG_RPM_NAME="librdkafka-devel"
+PKG_OSX_NAME="librdkafka"
+
 msg=0
-NORDKAFKA=1 # if pkg-config is not available then rdkafka++ will be disabled for higher chance of compilation success
+NORDKAFKA=1
 pkg-config --version >/dev/null 2>&1
 if [ $? -ne 0 ]; then
   echo "*** pkg-config is not installed."
@@ -14,40 +18,25 @@ else
   else
     NORDKAFKA=0
     RDKAFKA_LIB=`pkg-config --libs rdkafka++`
-    # expr -- "$lib" : ".*-lz$" >/dev/null  # -- for FreeBSD, #4652
-    # if [ $? -ne 0 ]; then
-    #   expr -- "$lib" : ".*-lz " >/dev/null
-    #   # would use \b in one expr but MacOS does not support \b
-    #   if [ $? -ne 0 ]; then
-    #     echo "*** pkg-config is installed and 'pkg-config --exists rdkafka++' succeeds but"
-    #     echo "*** 'pkg-config --libs rdkafka++' returns '${lib}' which does not include the standard -lz."
-    #     msg=1
-    #   fi
-    # fi
   fi
 fi
 
 if [ $msg -ne 0 ]; then
-  echo "*** Compilation will now be attempted and if it works you can ignore this message. In"
-  echo "*** particular, this should be the case on Mac where rdkafka++ is built in or pkg-config"
-  echo "*** is not installed. However, if compilation fails, try 'locate rdkafka++.h zconf.h' and"
-  echo "*** ensure the rdkafka++ development library is installed :"
-  echo "***   deb: rdkafka++ (Debian, Ubuntu, ...)"
-  echo "***   rpm: rdkafka++ (Fedora, EPEL, ...)"
-  echo "***   There is a rdkafka++ in brew for OSX but the built in rdkafka++ should work."
-  # echo "*** Note that zlib is required to compile R itself so you may find the advice in the R-admin"
-  # echo "*** guide helpful regarding zlib. On Debian/Ubuntu, zlib1g-dev is a dependency of r-base as"
-  # echo "*** shown by 'apt-cache showsrc r-base | grep ^Build-Depends | grep zlib', and therefore"
-  # echo "*** 'sudo apt-get build-dep r-base' should be sufficient too."
-  # echo "*** To silence this message, please ensure that :"
-  # echo "***   1) 'pkg-config --exists zlib' succeeds (i.e. \$? -eq 0)"
-  # echo "***   2) 'pkg-config --libs zlib' contains -lz"
-  # echo "*** Compilation will now be attempted ..."
+  echo "------------------------- ANTICONF ERROR ---------------------------"
+  echo "Configuration failed because pkg-config or rdkafka++ was not found. Try installing:"
+  echo "***   deb: $PKG_DEB_NAME (Debian, Ubuntu, ...)"
+  echo "***   rpm: $PKG_RPM_NAME (Fedora, CentOS, ...)"
+  echo "***   There is a $PKG_OSX_NAME in brew for OSX"
+  echo "*** To silence this message, please ensure that :"
+  echo "***   1) 'pkg-config --version' succeeds (i.e. \$? -ne 0)"
+  echo "***   2) 'pkg-config --exists rdkafka++' succeeds (i.e. \$? -eq 0)"
+  echo "***   3) 'pkg-config --libs rdkafka++' is similar to -L/usr/local/lib -lrdkafka++"
 else
-  version=`pkg-config --modversion zlib`
-  echo "rdkafka++ ${version} is available ok"
+  version=`pkg-config --modversion rdkafka++`
+  echo "rdkafka++ ${version} is available: OK"
+  echo "Using PKG_LIBS=$RDKAFKA_LIB"
 fi
 
-sed -e "s|@rdkafka_libs@|$RDKAFKA_LIB|" src/Makevars > src/Makevars.tmp && mv src/Makevars.tmp src/Makevars
+sed -e "s|@rdkafka_libs@|$RDKAFKA_LIB|" src/Makevars.in > src/Makevars
 
 exit 0
